### ISSUE TITLE
Big chungus

### ISSUE THREAD

**Issue by RiadZX** [JoenPoenMan/BotApp#1]
Hi!
I found an issue, there is no big chungus?? 😎👌👌😁😁😁😁🙂🙂🙂**BIG CHONKOS** AMOGUS

**Comment by RiadZX** [comment]
Issue is nog niet gefixed. **_Waarom niet?_** @JoenPoenMan

**Comment by JoenPoenMan** [comment]
Big chungoes may appear soon (:

**Comment by RiadZX** [comment]
Where?
